#!/usr/bin/env python3
"""The kanji of JIS X 0208 in JIS order, for the sidebar's name order (DATA_MODEL.md sidebar_sections
「セクションの中の並び順」, apps/shared/sidebar-order.json):

    python3 apps/shared/gen_jis_kanji.py

Level 1 (rows 16-47) is in on-reading order (院 イン before 修 シュウ), level 2 (rows 48-84) by radical and
strokes: the order Slack and Japanese collation (ICU ja) give kanji. The table is read from Python's EUC-JP codec
(JIS X 0208 row / cell = the two bytes minus 0xA0), so it needs no download; 6355 kanji, all in U+4E00-U+9FFF.
Each client gets the same string (the kanji in order) and indexes it once; the server does not sort sidebars.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = "Generated by apps/shared/gen_jis_kanji.py (JIS X 0208 rows 16-84 in JIS order); do not edit by hand."


def kanji() -> str:
    out = []
    for row in range(16, 85):
        for cell in range(1, 95):
            try:
                out.append(bytes([0xA0 + row, 0xA0 + cell]).decode("euc_jp"))
            except UnicodeDecodeError:
                continue  # the unused cells at the end of row 47 and row 84
    assert len(out) == 6355, len(out)
    assert all(0x4E00 <= ord(ch) <= 0x9FFF for ch in out)
    return "".join(out)


def main() -> None:
    order = kanji()
    (ROOT / "apps/desktop/src/ui/jisKanji.ts").write_text(
        f"// {HEADER}\n\n/** JIS X 0208 kanji (rows 16-84) in JIS order. */\nexport const JIS_KANJI =\n  \"{order}\";\n",
        encoding="utf-8",
    )
    (ROOT / "apps/ios/ChikuwaChat/UI/JISKanji.swift").write_text(
        f"// {HEADER}\n\n/// JIS X 0208 kanji (rows 16-84) in JIS order.\nenum JISKanji {{\n"
        f"    static let order = \"{order}\"\n}}\n",
        encoding="utf-8",
    )
    (ROOT / "apps/android/app/src/main/java/jp/chikuwachat/android/ui/JisKanji.kt").write_text(
        f"// {HEADER}\n\npackage jp.chikuwachat.android.ui\n\n/** JIS X 0208 kanji (rows 16-84) in JIS order. */\n"
        f"internal object JisKanji {{\n    const val ORDER = \"{order}\"\n}}\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
