package jp.chikuwachat.android.ui

// Generated from apps/shared/emoji.json by apps/shared/gen_emoji.py; do not edit by hand.

data class EmojiEntry(val shortcode: String, val glyph: String, val category: String, val keywords: String)

object EmojiData {
    val categories: List<Pair<String, String>> = listOf(
        "smileys" to "顔",
        "gestures" to "手・人",
        "hearts" to "ハート・記号",
        "objects" to "物",
        "nature" to "自然・動物",
        "food" to "食べ物",
        "travel" to "場所・乗り物",
        "flags" to "旗",
    )

    val all: List<EmojiEntry> = listOf(
        EmojiEntry("smile", "😄", "smileys", "happy grin 笑顔 にこ"),
        EmojiEntry("grinning", "😀", "smileys", "happy 笑顔"),
        EmojiEntry("laughing", "😆", "smileys", "haha 笑"),
        EmojiEntry("joy", "😂", "smileys", "lol tears 爆笑"),
        EmojiEntry("rofl", "🤣", "smileys", "lol rolling 笑い転げる"),
        EmojiEntry("sweat_smile", "😅", "smileys", "nervous 冷や汗 苦笑"),
        EmojiEntry("blush", "😊", "smileys", "shy にこにこ 照れ"),
        EmojiEntry("innocent", "😇", "smileys", "angel 天使"),
        EmojiEntry("wink", "😉", "smileys", "ウインク"),
        EmojiEntry("heart_eyes", "😍", "smileys", "love 大好き"),
        EmojiEntry("kissing_heart", "😘", "smileys", "kiss キス"),
        EmojiEntry("yum", "😋", "smileys", "delicious おいしい"),
        EmojiEntry("stuck_out_tongue", "😛", "smileys", "tongue べー"),
        EmojiEntry("thinking", "🤔", "smileys", "hmm 考え中 うーん"),
        EmojiEntry("neutral_face", "😐", "smileys", "meh 無表情"),
        EmojiEntry("expressionless", "😑", "smileys", "blank 無"),
        EmojiEntry("unamused", "😒", "smileys", "meh 不満"),
        EmojiEntry("rolling_eyes", "🙄", "smileys", "eyeroll やれやれ"),
        EmojiEntry("grimacing", "😬", "smileys", "awkward 気まずい"),
        EmojiEntry("relieved", "😌", "smileys", "phew ほっ 安心"),
        EmojiEntry("pensive", "😔", "smileys", "sad しょんぼり"),
        EmojiEntry("sleeping", "😴", "smileys", "zzz 睡眠 眠い"),
        EmojiEntry("mask", "😷", "smileys", "sick マスク 風邪"),
        EmojiEntry("face_with_thermometer", "🤒", "smileys", "sick fever 熱 体調不良"),
        EmojiEntry("dizzy_face", "😵", "smileys", "dizzy 目が回る"),
        EmojiEntry("exploding_head", "🤯", "smileys", "mind blown 衝撃"),
        EmojiEntry("sunglasses", "😎", "smileys", "cool かっこいい"),
        EmojiEntry("nerd_face", "🤓", "smileys", "nerd めがね"),
        EmojiEntry("confused", "😕", "smileys", "困惑 うーん"),
        EmojiEntry("worried", "😟", "smileys", "worry 心配"),
        EmojiEntry("slightly_frowning_face", "🙁", "smileys", "sad 残念"),
        EmojiEntry("open_mouth", "😮", "smileys", "wow surprised びっくり"),
        EmojiEntry("astonished", "😲", "smileys", "shocked 驚き"),
        EmojiEntry("flushed", "😳", "smileys", "embarrassed 照れる"),
        EmojiEntry("pleading_face", "🥺", "smileys", "please お願い うるうる"),
        EmojiEntry("cry", "😢", "smileys", "sad tear 泣く"),
        EmojiEntry("sob", "😭", "smileys", "cry 号泣"),
        EmojiEntry("scream", "😱", "smileys", "fear 悲鳴"),
        EmojiEntry("angry", "😠", "smileys", "mad 怒り"),
        EmojiEntry("rage", "😡", "smileys", "furious 激怒"),
        EmojiEntry("skull", "💀", "smileys", "dead 死 ヤバい"),
        EmojiEntry("ghost", "👻", "smileys", "boo おばけ"),
        EmojiEntry("robot", "🤖", "smileys", "bot ロボット"),
        EmojiEntry("saluting_face", "🫡", "smileys", "salute 了解 敬礼"),
        EmojiEntry("smiling_face_with_tear", "🥲", "smileys", "bittersweet 嬉し泣き"),
        EmojiEntry("partying_face", "🥳", "smileys", "party celebrate お祝い"),
        EmojiEntry("star_struck", "🤩", "smileys", "wow excited キラキラ"),
        EmojiEntry("hugs", "🤗", "smileys", "hug ハグ"),
        EmojiEntry("shushing_face", "🤫", "smileys", "quiet 静かに"),
        EmojiEntry("zipper_mouth_face", "🤐", "smileys", "secret 内緒"),
        EmojiEntry("melting_face", "🫠", "smileys", "melt とろける 暑い"),
        EmojiEntry("+1", "👍", "gestures", "thumbsup like ok いいね 了解"),
        EmojiEntry("-1", "👎", "gestures", "thumbsdown dislike よくない"),
        EmojiEntry("ok_hand", "👌", "gestures", "ok perfect オッケー"),
        EmojiEntry("clap", "👏", "gestures", "applause 拍手"),
        EmojiEntry("raised_hands", "🙌", "gestures", "hooray やった 万歳"),
        EmojiEntry("pray", "🙏", "gestures", "please thanks お願い ありがとう"),
        EmojiEntry("wave", "👋", "gestures", "hello bye 手を振る"),
        EmojiEntry("muscle", "💪", "gestures", "strong 筋肉 頑張る"),
        EmojiEntry("point_up", "☝️", "gestures", "up 指"),
        EmojiEntry("point_right", "👉", "gestures", "right 右"),
        EmojiEntry("point_left", "👈", "gestures", "left 左"),
        EmojiEntry("point_down", "👇", "gestures", "down 下"),
        EmojiEntry("v", "✌️", "gestures", "peace ピース"),
        EmojiEntry("crossed_fingers", "🤞", "gestures", "luck 願う"),
        EmojiEntry("handshake", "🤝", "gestures", "deal agree 握手"),
        EmojiEntry("writing_hand", "✍️", "gestures", "write 書く"),
        EmojiEntry("eyes", "👀", "gestures", "look watching 見てる"),
        EmojiEntry("brain", "🧠", "gestures", "think 脳"),
        EmojiEntry("bow", "🙇", "gestures", "sorry thanks おじぎ すみません"),
        EmojiEntry("raising_hand", "🙋", "gestures", "question me はい"),
        EmojiEntry("shrug", "🤷", "gestures", "dunno さあ"),
        EmojiEntry("facepalm", "🤦", "gestures", "oops やれやれ"),
        EmojiEntry("man_technologist", "👨‍💻", "gestures", "coding developer エンジニア"),
        EmojiEntry("woman_technologist", "👩‍💻", "gestures", "coding developer エンジニア"),
        EmojiEntry("heart", "❤️", "hearts", "love ハート 好き"),
        EmojiEntry("orange_heart", "🧡", "hearts", "love"),
        EmojiEntry("yellow_heart", "💛", "hearts", "love"),
        EmojiEntry("green_heart", "💚", "hearts", "love"),
        EmojiEntry("blue_heart", "💙", "hearts", "love"),
        EmojiEntry("purple_heart", "💜", "hearts", "love"),
        EmojiEntry("black_heart", "🖤", "hearts", "love"),
        EmojiEntry("white_heart", "🤍", "hearts", "love"),
        EmojiEntry("broken_heart", "💔", "hearts", "sad 失恋"),
        EmojiEntry("sparkling_heart", "💖", "hearts", "love キラキラ"),
        EmojiEntry("heartpulse", "💗", "hearts", "love"),
        EmojiEntry("two_hearts", "💕", "hearts", "love"),
        EmojiEntry("fire", "🔥", "hearts", "lit hot 熱い 最高"),
        EmojiEntry("sparkles", "✨", "hearts", "shiny new キラキラ"),
        EmojiEntry("star", "⭐", "hearts", "favorite 星"),
        EmojiEntry("star2", "🌟", "hearts", "glowing 星"),
        EmojiEntry("100", "💯", "hearts", "perfect 百点"),
        EmojiEntry("boom", "💥", "hearts", "explosion 爆発"),
        EmojiEntry("zap", "⚡", "hearts", "lightning fast 稲妻"),
        EmojiEntry("tada", "🎉", "hearts", "party celebrate 祝 おめでとう"),
        EmojiEntry("confetti_ball", "🎊", "hearts", "party 祝"),
        EmojiEntry("balloon", "🎈", "hearts", "party 風船"),
        EmojiEntry("gift", "🎁", "hearts", "present プレゼント"),
        EmojiEntry("trophy", "🏆", "hearts", "win 優勝"),
        EmojiEntry("medal", "🏅", "hearts", "award メダル"),
        EmojiEntry("white_check_mark", "✅", "hearts", "done check yes 完了 済み"),
        EmojiEntry("heavy_check_mark", "✔️", "hearts", "check done チェック"),
        EmojiEntry("x", "❌", "hearts", "no wrong バツ"),
        EmojiEntry("heavy_plus_sign", "➕", "hearts", "plus add 追加"),
        EmojiEntry("question", "❓", "hearts", "help 質問"),
        EmojiEntry("exclamation", "❗", "hearts", "alert 注意"),
        EmojiEntry("warning", "⚠️", "hearts", "caution 警告 注意"),
        EmojiEntry("no_entry", "⛔", "hearts", "stop 禁止"),
        EmojiEntry("arrow_right", "➡️", "hearts", "next 右"),
        EmojiEntry("arrow_left", "⬅️", "hearts", "back 左"),
        EmojiEntry("arrows_counterclockwise", "🔄", "hearts", "refresh retry 更新"),
        EmojiEntry("recycle", "♻️", "hearts", "recycle リサイクル"),
        EmojiEntry("bulb", "💡", "objects", "idea ひらめき アイデア"),
        EmojiEntry("memo", "📝", "objects", "note メモ 書く"),
        EmojiEntry("pushpin", "📌", "objects", "pin ピン"),
        EmojiEntry("bookmark", "🔖", "objects", "save しおり"),
        EmojiEntry("calendar", "📅", "objects", "date schedule 予定 カレンダー"),
        EmojiEntry("clock", "🕐", "objects", "time 時間"),
        EmojiEntry("alarm_clock", "⏰", "objects", "wake 目覚まし"),
        EmojiEntry("hourglass", "⏳", "objects", "wait waiting 待ち"),
        EmojiEntry("mag", "🔍", "objects", "search 検索"),
        EmojiEntry("lock", "🔒", "objects", "private 鍵"),
        EmojiEntry("unlock", "🔓", "objects", "open 解錠"),
        EmojiEntry("key", "🔑", "objects", "password 鍵"),
        EmojiEntry("bell", "🔔", "objects", "notification 通知"),
        EmojiEntry("no_bell", "🔕", "objects", "mute ミュート"),
        EmojiEntry("mega", "📣", "objects", "announce お知らせ"),
        EmojiEntry("loudspeaker", "📢", "objects", "announce 告知"),
        EmojiEntry("email", "📧", "objects", "mail メール"),
        EmojiEntry("inbox_tray", "📥", "objects", "inbox 受信"),
        EmojiEntry("outbox_tray", "📤", "objects", "outbox 送信"),
        EmojiEntry("package", "📦", "objects", "box release リリース 荷物"),
        EmojiEntry("file_folder", "📁", "objects", "folder フォルダ"),
        EmojiEntry("page_facing_up", "📄", "objects", "document 書類"),
        EmojiEntry("chart_with_upwards_trend", "📈", "objects", "growth 上昇 グラフ"),
        EmojiEntry("chart_with_downwards_trend", "📉", "objects", "decline 下降"),
        EmojiEntry("bar_chart", "📊", "objects", "stats グラフ"),
        EmojiEntry("clipboard", "📋", "objects", "list クリップボード"),
        EmojiEntry("computer", "💻", "objects", "laptop パソコン"),
        EmojiEntry("desktop_computer", "🖥️", "objects", "pc デスクトップ"),
        EmojiEntry("iphone", "📱", "objects", "phone スマホ"),
        EmojiEntry("keyboard", "⌨️", "objects", "type キーボード"),
        EmojiEntry("wrench", "🔧", "objects", "fix tool 修理 設定"),
        EmojiEntry("hammer", "🔨", "objects", "build 工具"),
        EmojiEntry("gear", "⚙️", "objects", "settings 設定"),
        EmojiEntry("bug", "🐛", "objects", "bug 虫 不具合"),
        EmojiEntry("rocket", "🚀", "objects", "launch ship deploy リリース 打ち上げ"),
        EmojiEntry("construction", "🚧", "objects", "wip 工事中"),
        EmojiEntry("books", "📚", "objects", "read study 本 勉強"),
        EmojiEntry("moneybag", "💰", "objects", "money お金"),
        EmojiEntry("dollar", "💵", "objects", "money ドル"),
        EmojiEntry("yen", "💴", "objects", "money 円"),
        EmojiEntry("shopping_cart", "🛒", "objects", "buy 買い物"),
        EmojiEntry("battery", "🔋", "objects", "power 電池"),
        EmojiEntry("link", "🔗", "objects", "url リンク"),
        EmojiEntry("paperclip", "📎", "objects", "attach 添付"),
        EmojiEntry("camera", "📷", "objects", "photo 写真"),
        EmojiEntry("movie_camera", "🎥", "objects", "video 動画"),
        EmojiEntry("microphone", "🎤", "objects", "sing mic マイク"),
        EmojiEntry("headphones", "🎧", "objects", "music 音楽"),
        EmojiEntry("musical_note", "🎵", "objects", "music 音楽"),
        EmojiEntry("art", "🎨", "objects", "design 絵"),
        EmojiEntry("game_die", "🎲", "objects", "random サイコロ"),
        EmojiEntry("soccer", "⚽", "objects", "football サッカー"),
        EmojiEntry("baseball", "⚾", "objects", "野球"),
        EmojiEntry("basketball", "🏀", "objects", "バスケ"),
        EmojiEntry("sunny", "☀️", "nature", "sun 晴れ"),
        EmojiEntry("cloud", "☁️", "nature", "cloudy 曇り"),
        EmojiEntry("umbrella", "☔", "nature", "rain 雨 傘"),
        EmojiEntry("snowflake", "❄️", "nature", "cold snow 雪"),
        EmojiEntry("rainbow", "🌈", "nature", "虹"),
        EmojiEntry("seedling", "🌱", "nature", "plant new 芽"),
        EmojiEntry("four_leaf_clover", "🍀", "nature", "luck クローバー"),
        EmojiEntry("cherry_blossom", "🌸", "nature", "sakura 桜 春"),
        EmojiEntry("maple_leaf", "🍁", "nature", "autumn 紅葉"),
        EmojiEntry("palm_tree", "🌴", "nature", "vacation 休暇 ヤシ"),
        EmojiEntry("dog", "🐶", "nature", "puppy 犬"),
        EmojiEntry("cat", "🐱", "nature", "kitty 猫"),
        EmojiEntry("mouse", "🐭", "nature", "ねずみ"),
        EmojiEntry("rabbit", "🐰", "nature", "bunny うさぎ"),
        EmojiEntry("bear", "🐻", "nature", "くま"),
        EmojiEntry("panda_face", "🐼", "nature", "パンダ"),
        EmojiEntry("fox_face", "🦊", "nature", "きつね"),
        EmojiEntry("pig", "🐷", "nature", "ぶた"),
        EmojiEntry("cow", "🐮", "nature", "うし"),
        EmojiEntry("monkey_face", "🐵", "nature", "さる"),
        EmojiEntry("chicken", "🐔", "nature", "にわとり"),
        EmojiEntry("penguin", "🐧", "nature", "ペンギン"),
        EmojiEntry("bird", "🐦", "nature", "鳥"),
        EmojiEntry("fish", "🐟", "nature", "魚"),
        EmojiEntry("whale", "🐳", "nature", "くじら"),
        EmojiEntry("dolphin", "🐬", "nature", "イルカ"),
        EmojiEntry("turtle", "🐢", "nature", "かめ"),
        EmojiEntry("snake", "🐍", "nature", "へび python"),
        EmojiEntry("bee", "🐝", "nature", "はち"),
        EmojiEntry("butterfly", "🦋", "nature", "ちょう"),
        EmojiEntry("dragon", "🐉", "nature", "龍"),
        EmojiEntry("unicorn", "🦄", "nature", "ユニコーン"),
        EmojiEntry("apple", "🍎", "food", "りんご"),
        EmojiEntry("banana", "🍌", "food", "バナナ"),
        EmojiEntry("strawberry", "🍓", "food", "いちご"),
        EmojiEntry("watermelon", "🍉", "food", "すいか"),
        EmojiEntry("rice_ball", "🍙", "food", "onigiri おにぎり"),
        EmojiEntry("bento", "🍱", "food", "lunch 弁当 昼休み"),
        EmojiEntry("ramen", "🍜", "food", "noodle ラーメン"),
        EmojiEntry("sushi", "🍣", "food", "寿司"),
        EmojiEntry("curry", "🍛", "food", "カレー"),
        EmojiEntry("rice", "🍚", "food", "ごはん"),
        EmojiEntry("dango", "🍡", "food", "だんご"),
        EmojiEntry("oden", "🍢", "food", "おでん"),
        EmojiEntry("pizza", "🍕", "food", "ピザ"),
        EmojiEntry("hamburger", "🍔", "food", "burger ハンバーガー"),
        EmojiEntry("fries", "🍟", "food", "ポテト"),
        EmojiEntry("bread", "🍞", "food", "パン"),
        EmojiEntry("egg", "🥚", "food", "たまご"),
        EmojiEntry("cake", "🍰", "food", "ケーキ"),
        EmojiEntry("birthday", "🎂", "food", "birthday 誕生日"),
        EmojiEntry("cookie", "🍪", "food", "クッキー"),
        EmojiEntry("doughnut", "🍩", "food", "ドーナツ"),
        EmojiEntry("chocolate_bar", "🍫", "food", "チョコ"),
        EmojiEntry("icecream", "🍦", "food", "アイス"),
        EmojiEntry("coffee", "☕", "food", "break コーヒー 休憩"),
        EmojiEntry("tea", "🍵", "food", "green tea お茶"),
        EmojiEntry("beer", "🍺", "food", "drink ビール 乾杯"),
        EmojiEntry("beers", "🍻", "food", "cheers 乾杯"),
        EmojiEntry("wine_glass", "🍷", "food", "ワイン"),
        EmojiEntry("sake", "🍶", "food", "日本酒"),
        EmojiEntry("cup_with_straw", "🥤", "food", "drink ジュース"),
        EmojiEntry("house", "🏠", "travel", "home 家 在宅"),
        EmojiEntry("office", "🏢", "travel", "work 会社 オフィス"),
        EmojiEntry("hospital", "🏥", "travel", "病院"),
        EmojiEntry("school", "🏫", "travel", "学校"),
        EmojiEntry("convenience_store", "🏪", "travel", "コンビニ"),
        EmojiEntry("mount_fuji", "🗻", "travel", "富士山"),
        EmojiEntry("tokyo_tower", "🗼", "travel", "東京タワー"),
        EmojiEntry("shinto_shrine", "⛩️", "travel", "神社"),
        EmojiEntry("car", "🚗", "travel", "drive 車"),
        EmojiEntry("bus", "🚌", "travel", "commute 移動 バス"),
        EmojiEntry("train", "🚃", "travel", "電車 通勤"),
        EmojiEntry("bullettrain_front", "🚅", "travel", "新幹線"),
        EmojiEntry("bike", "🚲", "travel", "自転車"),
        EmojiEntry("airplane", "✈️", "travel", "flight trip 飛行機 出張"),
        EmojiEntry("ship", "🚢", "travel", "船"),
        EmojiEntry("taxi", "🚕", "travel", "タクシー"),
        EmojiEntry("earth_asia", "🌏", "travel", "world 地球"),
        EmojiEntry("world_map", "🗺️", "travel", "map 地図"),
        EmojiEntry("jp", "🇯🇵", "flags", "japan 日本"),
        EmojiEntry("us", "🇺🇸", "flags", "usa アメリカ"),
        EmojiEntry("gb", "🇬🇧", "flags", "uk イギリス"),
        EmojiEntry("kr", "🇰🇷", "flags", "korea 韓国"),
        EmojiEntry("cn", "🇨🇳", "flags", "china 中国"),
        EmojiEntry("checkered_flag", "🏁", "flags", "finish ゴール"),
        EmojiEntry("triangular_flag_on_post", "🚩", "flags", "flag red 旗"),
    )
}
