package jp.chikuwachat.android.ui

import jp.chikuwachat.android.api.UserPublic
import jp.chikuwachat.android.platform.KeyValueStore
import jp.chikuwachat.android.sync.ChannelState
import java.text.Normalizer
import java.time.Instant
import java.util.Locale

/**
 * M37 (MOBILE_UI.md §6.2): how 「移動・検索」 (and the desktop's ⌘K) finds a conversation or a person by name. The rule and
 * its cases are apps/shared/jump-match.json (generated by apps/shared/gen_jump_match.py); JumpMatchTest reads them.
 */
object JumpMatch {
    /** After one of these, a name starts a new word (score 1). */
    // i18n: keep (separators the matcher ignores)
    private const val SEPARATORS = " -_./・　"

    /** NFKC (full-width / half-width forms), lower case, katakana as hiragana, no leading # or @, trimmed. */
    fun normalize(text: String): String {
        val folded = Normalizer.normalize(text, Normalizer.Form.NFKC).lowercase(Locale.ROOT).trim()
        val hiragana = buildString(folded.length) { folded.forEach { c -> append(if (c in 'ァ'..'ヶ') c - 0x60 else c) } }
        return hiragana.trimStart('#', '@').trim()
    }

    /**
     * 0: a name starts with the query; 1: a word in a name does (after a space, - _ . / ・); 2: a name contains it; null:
     * no match (or an empty query). The best over the names (a DM: the people's display names and usernames).
     */
    fun score(query: String, names: List<String>): Int? {
        val q = normalize(query)
        if (q.isEmpty()) return null
        var best: Int? = null
        for (name in names) {
            val n = normalize(name)
            val s = when {
                n.startsWith(q) -> 0
                (1 until n.length).any { n[it - 1] in SEPARATORS && n.startsWith(q, it) } -> 1
                n.contains(q) -> 2
                else -> continue
            }
            best = if (best == null) s else minOf(best, s)
        }
        return best
    }

    /** What a candidate is matched and ordered by. */
    data class Item(val id: String, val title: String, val names: List<String>, val unread: Boolean = false)

    /**
     * Matches only, by score, then unread first, then the normalized title in code-point order (UTF-16 units, the same on
     * every platform: no locale collation), then the id.
     */
    fun <T> rank(query: String, candidates: Collection<T>, item: (T) -> Item): List<T> =
        candidates
            .mapNotNull { candidate ->
                val described = item(candidate)
                score(query, described.names)?.let { Ranked(candidate, it, described) }
            }
            .sortedWith(compareBy<Ranked<T>> { it.score }.thenBy { !it.item.unread }.thenBy { normalize(it.item.title) }.thenBy { it.item.id })
            .map { it.value }

    private class Ranked<T>(val value: T, val score: Int, val item: Item)
}

/**
 * M37 (MOBILE_UI.md §6.1 ✏️, §6.2): what the jump screen and the new-message picker list, as pure functions (JumpTest).
 */
object Jump {
    /** Conversations while typing (§6.2). */
    const val MAX_CONVERSATIONS = 20

    /** People while typing (§6.2). */
    const val MAX_PEOPLE = 10

    /**
     * The names a conversation is found by: a channel its name; a DM (or group DM) the other members' display names and
     * usernames; my own DM my name. `userNames` gives someone's display name and username.
     */
    fun names(channel: ChannelState, meId: String?, userNames: (String) -> List<String>): List<String> {
        if (!channel.channel.isDm) return listOfNotNull(channel.channel.name)
        val others = (channel.channel.dmUserIds ?: emptyList()).filter { it != meId }
        return if (others.isEmpty()) meId?.let(userNames) ?: emptyList() else others.flatMap(userNames)
    }

    /** 「会話」: the ones I am in, not archived, that match (jump-match.json's order), at most [MAX_CONVERSATIONS]. */
    fun conversations(
        query: String,
        channels: Collection<ChannelState>,
        meId: String?,
        title: (ChannelState) -> String,
        userNames: (String) -> List<String>,
        now: Instant = Instant.now(),
    ): List<ChannelState> =
        JumpMatch.rank(query, channels.filter { it.isMember && !it.channel.archived }) {
            JumpMatch.Item(it.id, title(it), names(it, meId, userNames), unread = Channels.hasUnread(it, meId, now))
        }.take(MAX_CONVERSATIONS)

    /** 「人」: people not deactivated (me too: my own DM) that match by display name or username, at most [MAX_PEOPLE]. */
    fun people(query: String, users: Collection<UserPublic>): List<UserPublic> =
        rankPeople(query, users).take(MAX_PEOPLE)

    private fun rankPeople(query: String, users: Collection<UserPublic>): List<UserPublic> =
        JumpMatch.rank(query, users.filter { it.deactivatedAt == null }) { JumpMatch.Item(it.id, it.displayName, listOf(it.displayName, it.username)) }

    /** The new-message picker's rows: my channels, then public channels I can join, then people. */
    data class Destinations(val channels: List<ChannelState>, val joinable: List<ChannelState>, val people: List<UserPublic>)

    /**
     * ✏️ (§6.1): one search box over channels and people. Empty: my channels and the joinable public ones by name, and
     * everyone, me first, by name; typed: each group by the matching rule. Archived channels and deactivated people are
     * never offered.
     */
    fun destinations(
        query: String,
        channels: Collection<ChannelState>,
        users: Collection<UserPublic>,
        meId: String?,
        now: Instant = Instant.now(),
    ): Destinations {
        val mine = channels.filter { it.isMember && !it.channel.isDm && !it.channel.archived }
        val joinable = channels.filter { !it.isMember && it.channel.type == "public" && !it.channel.archived }
        if (query.isBlank()) {
            val byName = compareBy<ChannelState> { JumpMatch.normalize(it.channel.name ?: "") }.thenBy { it.id }
            return Destinations(
                channels = mine.sortedWith(byName),
                joinable = joinable.sortedWith(byName),
                people = users.filter { it.deactivatedAt == null }
                    .sortedWith(compareBy<UserPublic> { it.id != meId }.thenBy { JumpMatch.normalize(it.displayName) }.thenBy { it.id }),
            )
        }
        fun rankChannels(list: List<ChannelState>) = JumpMatch.rank(query, list) {
            JumpMatch.Item(it.id, it.channel.name ?: "", listOfNotNull(it.channel.name), unread = Channels.hasUnread(it, meId, now))
        }
        return Destinations(rankChannels(mine), rankChannels(joinable), rankPeople(query, users))
    }
}

/**
 * M37 (MOBILE_UI.md §6.2): 「最近の会話」, the conversations last opened on this device (any tab), newest first, at most
 * [MAX]; per account (`chikuwa.jump.recent:<server>|<username>`), never sent to the server.
 */
object RecentConversations {
    const val MAX = 10

    fun key(account: String): String = "chikuwa.jump.recent:$account"

    fun read(store: KeyValueStore, key: String): List<String> =
        store.getString(key)?.split("\n")?.filter { it.isNotEmpty() }?.distinct()?.take(MAX) ?: emptyList()

    /** Puts the conversation first (once) and returns the new list. */
    fun push(store: KeyValueStore, key: String, channelId: String): List<String> {
        val next = (listOf(channelId) + read(store, key).filter { it != channelId }).take(MAX)
        store.putString(key, next.joinToString("\n"))
        return next
    }

    fun clear(store: KeyValueStore, key: String) = store.putString(key, null)

    /** The ones still there to open: a conversation that vanished (left, deleted) is skipped, not shown broken. */
    fun shown(ids: List<String>, channel: (String) -> ChannelState?): List<ChannelState> =
        ids.mapNotNull(channel).filter { it.isMember || it.channel.type == "public" }
}
