// Generated from apps/shared/emoji.json by apps/shared/gen_emoji.py; do not edit by hand.

struct EmojiEntry: Hashable {
    let shortcode: String
    let glyph: String
    let category: String
    let keywords: String
}

enum EmojiData {
    static let categories: [(key: String, label: String)] = [
        ("smileys", "顔"),
        ("gestures", "手・人"),
        ("hearts", "ハート・記号"),
        ("objects", "物"),
        ("nature", "自然・動物"),
        ("food", "食べ物"),
        ("travel", "場所・乗り物"),
        ("flags", "旗"),
    ]

    static let all: [EmojiEntry] = [
        EmojiEntry(shortcode: "smile", glyph: "😄", category: "smileys", keywords: "happy grin 笑顔 にこ"),
        EmojiEntry(shortcode: "grinning", glyph: "😀", category: "smileys", keywords: "happy 笑顔"),
        EmojiEntry(shortcode: "laughing", glyph: "😆", category: "smileys", keywords: "haha 笑"),
        EmojiEntry(shortcode: "joy", glyph: "😂", category: "smileys", keywords: "lol tears 爆笑"),
        EmojiEntry(shortcode: "rofl", glyph: "🤣", category: "smileys", keywords: "lol rolling 笑い転げる"),
        EmojiEntry(shortcode: "sweat_smile", glyph: "😅", category: "smileys", keywords: "nervous 冷や汗 苦笑"),
        EmojiEntry(shortcode: "blush", glyph: "😊", category: "smileys", keywords: "shy にこにこ 照れ"),
        EmojiEntry(shortcode: "innocent", glyph: "😇", category: "smileys", keywords: "angel 天使"),
        EmojiEntry(shortcode: "wink", glyph: "😉", category: "smileys", keywords: "ウインク"),
        EmojiEntry(shortcode: "heart_eyes", glyph: "😍", category: "smileys", keywords: "love 大好き"),
        EmojiEntry(shortcode: "kissing_heart", glyph: "😘", category: "smileys", keywords: "kiss キス"),
        EmojiEntry(shortcode: "yum", glyph: "😋", category: "smileys", keywords: "delicious おいしい"),
        EmojiEntry(shortcode: "stuck_out_tongue", glyph: "😛", category: "smileys", keywords: "tongue べー"),
        EmojiEntry(shortcode: "thinking", glyph: "🤔", category: "smileys", keywords: "hmm 考え中 うーん"),
        EmojiEntry(shortcode: "neutral_face", glyph: "😐", category: "smileys", keywords: "meh 無表情"),
        EmojiEntry(shortcode: "expressionless", glyph: "😑", category: "smileys", keywords: "blank 無"),
        EmojiEntry(shortcode: "unamused", glyph: "😒", category: "smileys", keywords: "meh 不満"),
        EmojiEntry(shortcode: "rolling_eyes", glyph: "🙄", category: "smileys", keywords: "eyeroll やれやれ"),
        EmojiEntry(shortcode: "grimacing", glyph: "😬", category: "smileys", keywords: "awkward 気まずい"),
        EmojiEntry(shortcode: "relieved", glyph: "😌", category: "smileys", keywords: "phew ほっ 安心"),
        EmojiEntry(shortcode: "pensive", glyph: "😔", category: "smileys", keywords: "sad しょんぼり"),
        EmojiEntry(shortcode: "sleeping", glyph: "😴", category: "smileys", keywords: "zzz 睡眠 眠い"),
        EmojiEntry(shortcode: "mask", glyph: "😷", category: "smileys", keywords: "sick マスク 風邪"),
        EmojiEntry(shortcode: "face_with_thermometer", glyph: "🤒", category: "smileys", keywords: "sick fever 熱 体調不良"),
        EmojiEntry(shortcode: "dizzy_face", glyph: "😵", category: "smileys", keywords: "dizzy 目が回る"),
        EmojiEntry(shortcode: "exploding_head", glyph: "🤯", category: "smileys", keywords: "mind blown 衝撃"),
        EmojiEntry(shortcode: "sunglasses", glyph: "😎", category: "smileys", keywords: "cool かっこいい"),
        EmojiEntry(shortcode: "nerd_face", glyph: "🤓", category: "smileys", keywords: "nerd めがね"),
        EmojiEntry(shortcode: "confused", glyph: "😕", category: "smileys", keywords: "困惑 うーん"),
        EmojiEntry(shortcode: "worried", glyph: "😟", category: "smileys", keywords: "worry 心配"),
        EmojiEntry(shortcode: "slightly_frowning_face", glyph: "🙁", category: "smileys", keywords: "sad 残念"),
        EmojiEntry(shortcode: "open_mouth", glyph: "😮", category: "smileys", keywords: "wow surprised びっくり"),
        EmojiEntry(shortcode: "astonished", glyph: "😲", category: "smileys", keywords: "shocked 驚き"),
        EmojiEntry(shortcode: "flushed", glyph: "😳", category: "smileys", keywords: "embarrassed 照れる"),
        EmojiEntry(shortcode: "pleading_face", glyph: "🥺", category: "smileys", keywords: "please お願い うるうる"),
        EmojiEntry(shortcode: "cry", glyph: "😢", category: "smileys", keywords: "sad tear 泣く"),
        EmojiEntry(shortcode: "sob", glyph: "😭", category: "smileys", keywords: "cry 号泣"),
        EmojiEntry(shortcode: "scream", glyph: "😱", category: "smileys", keywords: "fear 悲鳴"),
        EmojiEntry(shortcode: "angry", glyph: "😠", category: "smileys", keywords: "mad 怒り"),
        EmojiEntry(shortcode: "rage", glyph: "😡", category: "smileys", keywords: "furious 激怒"),
        EmojiEntry(shortcode: "skull", glyph: "💀", category: "smileys", keywords: "dead 死 ヤバい"),
        EmojiEntry(shortcode: "ghost", glyph: "👻", category: "smileys", keywords: "boo おばけ"),
        EmojiEntry(shortcode: "robot", glyph: "🤖", category: "smileys", keywords: "bot ロボット"),
        EmojiEntry(shortcode: "saluting_face", glyph: "🫡", category: "smileys", keywords: "salute 了解 敬礼"),
        EmojiEntry(shortcode: "smiling_face_with_tear", glyph: "🥲", category: "smileys", keywords: "bittersweet 嬉し泣き"),
        EmojiEntry(shortcode: "partying_face", glyph: "🥳", category: "smileys", keywords: "party celebrate お祝い"),
        EmojiEntry(shortcode: "star_struck", glyph: "🤩", category: "smileys", keywords: "wow excited キラキラ"),
        EmojiEntry(shortcode: "hugs", glyph: "🤗", category: "smileys", keywords: "hug ハグ"),
        EmojiEntry(shortcode: "shushing_face", glyph: "🤫", category: "smileys", keywords: "quiet 静かに"),
        EmojiEntry(shortcode: "zipper_mouth_face", glyph: "🤐", category: "smileys", keywords: "secret 内緒"),
        EmojiEntry(shortcode: "melting_face", glyph: "🫠", category: "smileys", keywords: "melt とろける 暑い"),
        EmojiEntry(shortcode: "+1", glyph: "👍", category: "gestures", keywords: "thumbsup like ok いいね 了解"),
        EmojiEntry(shortcode: "-1", glyph: "👎", category: "gestures", keywords: "thumbsdown dislike よくない"),
        EmojiEntry(shortcode: "ok_hand", glyph: "👌", category: "gestures", keywords: "ok perfect オッケー"),
        EmojiEntry(shortcode: "clap", glyph: "👏", category: "gestures", keywords: "applause 拍手"),
        EmojiEntry(shortcode: "raised_hands", glyph: "🙌", category: "gestures", keywords: "hooray やった 万歳"),
        EmojiEntry(shortcode: "pray", glyph: "🙏", category: "gestures", keywords: "please thanks お願い ありがとう"),
        EmojiEntry(shortcode: "wave", glyph: "👋", category: "gestures", keywords: "hello bye 手を振る"),
        EmojiEntry(shortcode: "muscle", glyph: "💪", category: "gestures", keywords: "strong 筋肉 頑張る"),
        EmojiEntry(shortcode: "point_up", glyph: "☝️", category: "gestures", keywords: "up 指"),
        EmojiEntry(shortcode: "point_right", glyph: "👉", category: "gestures", keywords: "right 右"),
        EmojiEntry(shortcode: "point_left", glyph: "👈", category: "gestures", keywords: "left 左"),
        EmojiEntry(shortcode: "point_down", glyph: "👇", category: "gestures", keywords: "down 下"),
        EmojiEntry(shortcode: "v", glyph: "✌️", category: "gestures", keywords: "peace ピース"),
        EmojiEntry(shortcode: "crossed_fingers", glyph: "🤞", category: "gestures", keywords: "luck 願う"),
        EmojiEntry(shortcode: "handshake", glyph: "🤝", category: "gestures", keywords: "deal agree 握手"),
        EmojiEntry(shortcode: "writing_hand", glyph: "✍️", category: "gestures", keywords: "write 書く"),
        EmojiEntry(shortcode: "eyes", glyph: "👀", category: "gestures", keywords: "look watching 見てる"),
        EmojiEntry(shortcode: "brain", glyph: "🧠", category: "gestures", keywords: "think 脳"),
        EmojiEntry(shortcode: "bow", glyph: "🙇", category: "gestures", keywords: "sorry thanks おじぎ すみません"),
        EmojiEntry(shortcode: "raising_hand", glyph: "🙋", category: "gestures", keywords: "question me はい"),
        EmojiEntry(shortcode: "shrug", glyph: "🤷", category: "gestures", keywords: "dunno さあ"),
        EmojiEntry(shortcode: "facepalm", glyph: "🤦", category: "gestures", keywords: "oops やれやれ"),
        EmojiEntry(shortcode: "man_technologist", glyph: "👨‍💻", category: "gestures", keywords: "coding developer エンジニア"),
        EmojiEntry(shortcode: "woman_technologist", glyph: "👩‍💻", category: "gestures", keywords: "coding developer エンジニア"),
        EmojiEntry(shortcode: "heart", glyph: "❤️", category: "hearts", keywords: "love ハート 好き"),
        EmojiEntry(shortcode: "orange_heart", glyph: "🧡", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "yellow_heart", glyph: "💛", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "green_heart", glyph: "💚", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "blue_heart", glyph: "💙", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "purple_heart", glyph: "💜", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "black_heart", glyph: "🖤", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "white_heart", glyph: "🤍", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "broken_heart", glyph: "💔", category: "hearts", keywords: "sad 失恋"),
        EmojiEntry(shortcode: "sparkling_heart", glyph: "💖", category: "hearts", keywords: "love キラキラ"),
        EmojiEntry(shortcode: "heartpulse", glyph: "💗", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "two_hearts", glyph: "💕", category: "hearts", keywords: "love"),
        EmojiEntry(shortcode: "fire", glyph: "🔥", category: "hearts", keywords: "lit hot 熱い 最高"),
        EmojiEntry(shortcode: "sparkles", glyph: "✨", category: "hearts", keywords: "shiny new キラキラ"),
        EmojiEntry(shortcode: "star", glyph: "⭐", category: "hearts", keywords: "favorite 星"),
        EmojiEntry(shortcode: "star2", glyph: "🌟", category: "hearts", keywords: "glowing 星"),
        EmojiEntry(shortcode: "100", glyph: "💯", category: "hearts", keywords: "perfect 百点"),
        EmojiEntry(shortcode: "boom", glyph: "💥", category: "hearts", keywords: "explosion 爆発"),
        EmojiEntry(shortcode: "zap", glyph: "⚡", category: "hearts", keywords: "lightning fast 稲妻"),
        EmojiEntry(shortcode: "tada", glyph: "🎉", category: "hearts", keywords: "party celebrate 祝 おめでとう"),
        EmojiEntry(shortcode: "confetti_ball", glyph: "🎊", category: "hearts", keywords: "party 祝"),
        EmojiEntry(shortcode: "balloon", glyph: "🎈", category: "hearts", keywords: "party 風船"),
        EmojiEntry(shortcode: "gift", glyph: "🎁", category: "hearts", keywords: "present プレゼント"),
        EmojiEntry(shortcode: "trophy", glyph: "🏆", category: "hearts", keywords: "win 優勝"),
        EmojiEntry(shortcode: "medal", glyph: "🏅", category: "hearts", keywords: "award メダル"),
        EmojiEntry(shortcode: "white_check_mark", glyph: "✅", category: "hearts", keywords: "done check yes 完了 済み"),
        EmojiEntry(shortcode: "heavy_check_mark", glyph: "✔️", category: "hearts", keywords: "check done チェック"),
        EmojiEntry(shortcode: "x", glyph: "❌", category: "hearts", keywords: "no wrong バツ"),
        EmojiEntry(shortcode: "heavy_plus_sign", glyph: "➕", category: "hearts", keywords: "plus add 追加"),
        EmojiEntry(shortcode: "question", glyph: "❓", category: "hearts", keywords: "help 質問"),
        EmojiEntry(shortcode: "exclamation", glyph: "❗", category: "hearts", keywords: "alert 注意"),
        EmojiEntry(shortcode: "warning", glyph: "⚠️", category: "hearts", keywords: "caution 警告 注意"),
        EmojiEntry(shortcode: "no_entry", glyph: "⛔", category: "hearts", keywords: "stop 禁止"),
        EmojiEntry(shortcode: "arrow_right", glyph: "➡️", category: "hearts", keywords: "next 右"),
        EmojiEntry(shortcode: "arrow_left", glyph: "⬅️", category: "hearts", keywords: "back 左"),
        EmojiEntry(shortcode: "arrows_counterclockwise", glyph: "🔄", category: "hearts", keywords: "refresh retry 更新"),
        EmojiEntry(shortcode: "recycle", glyph: "♻️", category: "hearts", keywords: "recycle リサイクル"),
        EmojiEntry(shortcode: "bulb", glyph: "💡", category: "objects", keywords: "idea ひらめき アイデア"),
        EmojiEntry(shortcode: "memo", glyph: "📝", category: "objects", keywords: "note メモ 書く"),
        EmojiEntry(shortcode: "pushpin", glyph: "📌", category: "objects", keywords: "pin ピン"),
        EmojiEntry(shortcode: "bookmark", glyph: "🔖", category: "objects", keywords: "save しおり"),
        EmojiEntry(shortcode: "calendar", glyph: "📅", category: "objects", keywords: "date schedule 予定 カレンダー"),
        EmojiEntry(shortcode: "clock", glyph: "🕐", category: "objects", keywords: "time 時間"),
        EmojiEntry(shortcode: "alarm_clock", glyph: "⏰", category: "objects", keywords: "wake 目覚まし"),
        EmojiEntry(shortcode: "hourglass", glyph: "⏳", category: "objects", keywords: "wait waiting 待ち"),
        EmojiEntry(shortcode: "mag", glyph: "🔍", category: "objects", keywords: "search 検索"),
        EmojiEntry(shortcode: "lock", glyph: "🔒", category: "objects", keywords: "private 鍵"),
        EmojiEntry(shortcode: "unlock", glyph: "🔓", category: "objects", keywords: "open 解錠"),
        EmojiEntry(shortcode: "key", glyph: "🔑", category: "objects", keywords: "password 鍵"),
        EmojiEntry(shortcode: "bell", glyph: "🔔", category: "objects", keywords: "notification 通知"),
        EmojiEntry(shortcode: "no_bell", glyph: "🔕", category: "objects", keywords: "mute ミュート"),
        EmojiEntry(shortcode: "mega", glyph: "📣", category: "objects", keywords: "announce お知らせ"),
        EmojiEntry(shortcode: "loudspeaker", glyph: "📢", category: "objects", keywords: "announce 告知"),
        EmojiEntry(shortcode: "email", glyph: "📧", category: "objects", keywords: "mail メール"),
        EmojiEntry(shortcode: "inbox_tray", glyph: "📥", category: "objects", keywords: "inbox 受信"),
        EmojiEntry(shortcode: "outbox_tray", glyph: "📤", category: "objects", keywords: "outbox 送信"),
        EmojiEntry(shortcode: "package", glyph: "📦", category: "objects", keywords: "box release リリース 荷物"),
        EmojiEntry(shortcode: "file_folder", glyph: "📁", category: "objects", keywords: "folder フォルダ"),
        EmojiEntry(shortcode: "page_facing_up", glyph: "📄", category: "objects", keywords: "document 書類"),
        EmojiEntry(shortcode: "chart_with_upwards_trend", glyph: "📈", category: "objects", keywords: "growth 上昇 グラフ"),
        EmojiEntry(shortcode: "chart_with_downwards_trend", glyph: "📉", category: "objects", keywords: "decline 下降"),
        EmojiEntry(shortcode: "bar_chart", glyph: "📊", category: "objects", keywords: "stats グラフ"),
        EmojiEntry(shortcode: "clipboard", glyph: "📋", category: "objects", keywords: "list クリップボード"),
        EmojiEntry(shortcode: "computer", glyph: "💻", category: "objects", keywords: "laptop パソコン"),
        EmojiEntry(shortcode: "desktop_computer", glyph: "🖥️", category: "objects", keywords: "pc デスクトップ"),
        EmojiEntry(shortcode: "iphone", glyph: "📱", category: "objects", keywords: "phone スマホ"),
        EmojiEntry(shortcode: "keyboard", glyph: "⌨️", category: "objects", keywords: "type キーボード"),
        EmojiEntry(shortcode: "wrench", glyph: "🔧", category: "objects", keywords: "fix tool 修理 設定"),
        EmojiEntry(shortcode: "hammer", glyph: "🔨", category: "objects", keywords: "build 工具"),
        EmojiEntry(shortcode: "gear", glyph: "⚙️", category: "objects", keywords: "settings 設定"),
        EmojiEntry(shortcode: "bug", glyph: "🐛", category: "objects", keywords: "bug 虫 不具合"),
        EmojiEntry(shortcode: "rocket", glyph: "🚀", category: "objects", keywords: "launch ship deploy リリース 打ち上げ"),
        EmojiEntry(shortcode: "construction", glyph: "🚧", category: "objects", keywords: "wip 工事中"),
        EmojiEntry(shortcode: "books", glyph: "📚", category: "objects", keywords: "read study 本 勉強"),
        EmojiEntry(shortcode: "moneybag", glyph: "💰", category: "objects", keywords: "money お金"),
        EmojiEntry(shortcode: "dollar", glyph: "💵", category: "objects", keywords: "money ドル"),
        EmojiEntry(shortcode: "yen", glyph: "💴", category: "objects", keywords: "money 円"),
        EmojiEntry(shortcode: "shopping_cart", glyph: "🛒", category: "objects", keywords: "buy 買い物"),
        EmojiEntry(shortcode: "battery", glyph: "🔋", category: "objects", keywords: "power 電池"),
        EmojiEntry(shortcode: "link", glyph: "🔗", category: "objects", keywords: "url リンク"),
        EmojiEntry(shortcode: "paperclip", glyph: "📎", category: "objects", keywords: "attach 添付"),
        EmojiEntry(shortcode: "camera", glyph: "📷", category: "objects", keywords: "photo 写真"),
        EmojiEntry(shortcode: "movie_camera", glyph: "🎥", category: "objects", keywords: "video 動画"),
        EmojiEntry(shortcode: "microphone", glyph: "🎤", category: "objects", keywords: "sing mic マイク"),
        EmojiEntry(shortcode: "headphones", glyph: "🎧", category: "objects", keywords: "music 音楽"),
        EmojiEntry(shortcode: "musical_note", glyph: "🎵", category: "objects", keywords: "music 音楽"),
        EmojiEntry(shortcode: "art", glyph: "🎨", category: "objects", keywords: "design 絵"),
        EmojiEntry(shortcode: "game_die", glyph: "🎲", category: "objects", keywords: "random サイコロ"),
        EmojiEntry(shortcode: "soccer", glyph: "⚽", category: "objects", keywords: "football サッカー"),
        EmojiEntry(shortcode: "baseball", glyph: "⚾", category: "objects", keywords: "野球"),
        EmojiEntry(shortcode: "basketball", glyph: "🏀", category: "objects", keywords: "バスケ"),
        EmojiEntry(shortcode: "sunny", glyph: "☀️", category: "nature", keywords: "sun 晴れ"),
        EmojiEntry(shortcode: "cloud", glyph: "☁️", category: "nature", keywords: "cloudy 曇り"),
        EmojiEntry(shortcode: "umbrella", glyph: "☔", category: "nature", keywords: "rain 雨 傘"),
        EmojiEntry(shortcode: "snowflake", glyph: "❄️", category: "nature", keywords: "cold snow 雪"),
        EmojiEntry(shortcode: "rainbow", glyph: "🌈", category: "nature", keywords: "虹"),
        EmojiEntry(shortcode: "seedling", glyph: "🌱", category: "nature", keywords: "plant new 芽"),
        EmojiEntry(shortcode: "four_leaf_clover", glyph: "🍀", category: "nature", keywords: "luck クローバー"),
        EmojiEntry(shortcode: "cherry_blossom", glyph: "🌸", category: "nature", keywords: "sakura 桜 春"),
        EmojiEntry(shortcode: "maple_leaf", glyph: "🍁", category: "nature", keywords: "autumn 紅葉"),
        EmojiEntry(shortcode: "palm_tree", glyph: "🌴", category: "nature", keywords: "vacation 休暇 ヤシ"),
        EmojiEntry(shortcode: "dog", glyph: "🐶", category: "nature", keywords: "puppy 犬"),
        EmojiEntry(shortcode: "cat", glyph: "🐱", category: "nature", keywords: "kitty 猫"),
        EmojiEntry(shortcode: "mouse", glyph: "🐭", category: "nature", keywords: "ねずみ"),
        EmojiEntry(shortcode: "rabbit", glyph: "🐰", category: "nature", keywords: "bunny うさぎ"),
        EmojiEntry(shortcode: "bear", glyph: "🐻", category: "nature", keywords: "くま"),
        EmojiEntry(shortcode: "panda_face", glyph: "🐼", category: "nature", keywords: "パンダ"),
        EmojiEntry(shortcode: "fox_face", glyph: "🦊", category: "nature", keywords: "きつね"),
        EmojiEntry(shortcode: "pig", glyph: "🐷", category: "nature", keywords: "ぶた"),
        EmojiEntry(shortcode: "cow", glyph: "🐮", category: "nature", keywords: "うし"),
        EmojiEntry(shortcode: "monkey_face", glyph: "🐵", category: "nature", keywords: "さる"),
        EmojiEntry(shortcode: "chicken", glyph: "🐔", category: "nature", keywords: "にわとり"),
        EmojiEntry(shortcode: "penguin", glyph: "🐧", category: "nature", keywords: "ペンギン"),
        EmojiEntry(shortcode: "bird", glyph: "🐦", category: "nature", keywords: "鳥"),
        EmojiEntry(shortcode: "fish", glyph: "🐟", category: "nature", keywords: "魚"),
        EmojiEntry(shortcode: "whale", glyph: "🐳", category: "nature", keywords: "くじら"),
        EmojiEntry(shortcode: "dolphin", glyph: "🐬", category: "nature", keywords: "イルカ"),
        EmojiEntry(shortcode: "turtle", glyph: "🐢", category: "nature", keywords: "かめ"),
        EmojiEntry(shortcode: "snake", glyph: "🐍", category: "nature", keywords: "へび python"),
        EmojiEntry(shortcode: "bee", glyph: "🐝", category: "nature", keywords: "はち"),
        EmojiEntry(shortcode: "butterfly", glyph: "🦋", category: "nature", keywords: "ちょう"),
        EmojiEntry(shortcode: "dragon", glyph: "🐉", category: "nature", keywords: "龍"),
        EmojiEntry(shortcode: "unicorn", glyph: "🦄", category: "nature", keywords: "ユニコーン"),
        EmojiEntry(shortcode: "apple", glyph: "🍎", category: "food", keywords: "りんご"),
        EmojiEntry(shortcode: "banana", glyph: "🍌", category: "food", keywords: "バナナ"),
        EmojiEntry(shortcode: "strawberry", glyph: "🍓", category: "food", keywords: "いちご"),
        EmojiEntry(shortcode: "watermelon", glyph: "🍉", category: "food", keywords: "すいか"),
        EmojiEntry(shortcode: "rice_ball", glyph: "🍙", category: "food", keywords: "onigiri おにぎり"),
        EmojiEntry(shortcode: "bento", glyph: "🍱", category: "food", keywords: "lunch 弁当 昼休み"),
        EmojiEntry(shortcode: "ramen", glyph: "🍜", category: "food", keywords: "noodle ラーメン"),
        EmojiEntry(shortcode: "sushi", glyph: "🍣", category: "food", keywords: "寿司"),
        EmojiEntry(shortcode: "curry", glyph: "🍛", category: "food", keywords: "カレー"),
        EmojiEntry(shortcode: "rice", glyph: "🍚", category: "food", keywords: "ごはん"),
        EmojiEntry(shortcode: "dango", glyph: "🍡", category: "food", keywords: "だんご"),
        EmojiEntry(shortcode: "oden", glyph: "🍢", category: "food", keywords: "おでん"),
        EmojiEntry(shortcode: "pizza", glyph: "🍕", category: "food", keywords: "ピザ"),
        EmojiEntry(shortcode: "hamburger", glyph: "🍔", category: "food", keywords: "burger ハンバーガー"),
        EmojiEntry(shortcode: "fries", glyph: "🍟", category: "food", keywords: "ポテト"),
        EmojiEntry(shortcode: "bread", glyph: "🍞", category: "food", keywords: "パン"),
        EmojiEntry(shortcode: "egg", glyph: "🥚", category: "food", keywords: "たまご"),
        EmojiEntry(shortcode: "cake", glyph: "🍰", category: "food", keywords: "ケーキ"),
        EmojiEntry(shortcode: "birthday", glyph: "🎂", category: "food", keywords: "birthday 誕生日"),
        EmojiEntry(shortcode: "cookie", glyph: "🍪", category: "food", keywords: "クッキー"),
        EmojiEntry(shortcode: "doughnut", glyph: "🍩", category: "food", keywords: "ドーナツ"),
        EmojiEntry(shortcode: "chocolate_bar", glyph: "🍫", category: "food", keywords: "チョコ"),
        EmojiEntry(shortcode: "icecream", glyph: "🍦", category: "food", keywords: "アイス"),
        EmojiEntry(shortcode: "coffee", glyph: "☕", category: "food", keywords: "break コーヒー 休憩"),
        EmojiEntry(shortcode: "tea", glyph: "🍵", category: "food", keywords: "green tea お茶"),
        EmojiEntry(shortcode: "beer", glyph: "🍺", category: "food", keywords: "drink ビール 乾杯"),
        EmojiEntry(shortcode: "beers", glyph: "🍻", category: "food", keywords: "cheers 乾杯"),
        EmojiEntry(shortcode: "wine_glass", glyph: "🍷", category: "food", keywords: "ワイン"),
        EmojiEntry(shortcode: "sake", glyph: "🍶", category: "food", keywords: "日本酒"),
        EmojiEntry(shortcode: "cup_with_straw", glyph: "🥤", category: "food", keywords: "drink ジュース"),
        EmojiEntry(shortcode: "house", glyph: "🏠", category: "travel", keywords: "home 家 在宅"),
        EmojiEntry(shortcode: "office", glyph: "🏢", category: "travel", keywords: "work 会社 オフィス"),
        EmojiEntry(shortcode: "hospital", glyph: "🏥", category: "travel", keywords: "病院"),
        EmojiEntry(shortcode: "school", glyph: "🏫", category: "travel", keywords: "学校"),
        EmojiEntry(shortcode: "convenience_store", glyph: "🏪", category: "travel", keywords: "コンビニ"),
        EmojiEntry(shortcode: "mount_fuji", glyph: "🗻", category: "travel", keywords: "富士山"),
        EmojiEntry(shortcode: "tokyo_tower", glyph: "🗼", category: "travel", keywords: "東京タワー"),
        EmojiEntry(shortcode: "shinto_shrine", glyph: "⛩️", category: "travel", keywords: "神社"),
        EmojiEntry(shortcode: "car", glyph: "🚗", category: "travel", keywords: "drive 車"),
        EmojiEntry(shortcode: "bus", glyph: "🚌", category: "travel", keywords: "commute 移動 バス"),
        EmojiEntry(shortcode: "train", glyph: "🚃", category: "travel", keywords: "電車 通勤"),
        EmojiEntry(shortcode: "bullettrain_front", glyph: "🚅", category: "travel", keywords: "新幹線"),
        EmojiEntry(shortcode: "bike", glyph: "🚲", category: "travel", keywords: "自転車"),
        EmojiEntry(shortcode: "airplane", glyph: "✈️", category: "travel", keywords: "flight trip 飛行機 出張"),
        EmojiEntry(shortcode: "ship", glyph: "🚢", category: "travel", keywords: "船"),
        EmojiEntry(shortcode: "taxi", glyph: "🚕", category: "travel", keywords: "タクシー"),
        EmojiEntry(shortcode: "earth_asia", glyph: "🌏", category: "travel", keywords: "world 地球"),
        EmojiEntry(shortcode: "world_map", glyph: "🗺️", category: "travel", keywords: "map 地図"),
        EmojiEntry(shortcode: "jp", glyph: "🇯🇵", category: "flags", keywords: "japan 日本"),
        EmojiEntry(shortcode: "us", glyph: "🇺🇸", category: "flags", keywords: "usa アメリカ"),
        EmojiEntry(shortcode: "gb", glyph: "🇬🇧", category: "flags", keywords: "uk イギリス"),
        EmojiEntry(shortcode: "kr", glyph: "🇰🇷", category: "flags", keywords: "korea 韓国"),
        EmojiEntry(shortcode: "cn", glyph: "🇨🇳", category: "flags", keywords: "china 中国"),
        EmojiEntry(shortcode: "checkered_flag", glyph: "🏁", category: "flags", keywords: "finish ゴール"),
        EmojiEntry(shortcode: "triangular_flag_on_post", glyph: "🚩", category: "flags", keywords: "flag red 旗"),
    ]
}
