// Generated from apps/shared/emoji.json by apps/shared/gen_emoji.py; do not edit by hand.

export interface EmojiEntry {
  shortcode: string;
  glyph: string;
  category: string;
  keywords: string;
}

export const EMOJI_CATEGORIES: Array<[string, string]> = [
  ["smileys", "顔"],
  ["gestures", "手・人"],
  ["hearts", "ハート・記号"],
  ["objects", "物"],
  ["nature", "自然・動物"],
  ["food", "食べ物"],
  ["travel", "場所・乗り物"],
  ["flags", "旗"],
];

export const EMOJI: EmojiEntry[] = [
  { shortcode: "smile", glyph: "😄", category: "smileys", keywords: "happy grin 笑顔 にこ" },
  { shortcode: "grinning", glyph: "😀", category: "smileys", keywords: "happy 笑顔" },
  { shortcode: "laughing", glyph: "😆", category: "smileys", keywords: "haha 笑" },
  { shortcode: "joy", glyph: "😂", category: "smileys", keywords: "lol tears 爆笑" },
  { shortcode: "rofl", glyph: "🤣", category: "smileys", keywords: "lol rolling 笑い転げる" },
  { shortcode: "sweat_smile", glyph: "😅", category: "smileys", keywords: "nervous 冷や汗 苦笑" },
  { shortcode: "blush", glyph: "😊", category: "smileys", keywords: "shy にこにこ 照れ" },
  { shortcode: "innocent", glyph: "😇", category: "smileys", keywords: "angel 天使" },
  { shortcode: "wink", glyph: "😉", category: "smileys", keywords: "ウインク" },
  { shortcode: "heart_eyes", glyph: "😍", category: "smileys", keywords: "love 大好き" },
  { shortcode: "kissing_heart", glyph: "😘", category: "smileys", keywords: "kiss キス" },
  { shortcode: "yum", glyph: "😋", category: "smileys", keywords: "delicious おいしい" },
  { shortcode: "stuck_out_tongue", glyph: "😛", category: "smileys", keywords: "tongue べー" },
  { shortcode: "thinking", glyph: "🤔", category: "smileys", keywords: "hmm 考え中 うーん" },
  { shortcode: "neutral_face", glyph: "😐", category: "smileys", keywords: "meh 無表情" },
  { shortcode: "expressionless", glyph: "😑", category: "smileys", keywords: "blank 無" },
  { shortcode: "unamused", glyph: "😒", category: "smileys", keywords: "meh 不満" },
  { shortcode: "rolling_eyes", glyph: "🙄", category: "smileys", keywords: "eyeroll やれやれ" },
  { shortcode: "grimacing", glyph: "😬", category: "smileys", keywords: "awkward 気まずい" },
  { shortcode: "relieved", glyph: "😌", category: "smileys", keywords: "phew ほっ 安心" },
  { shortcode: "pensive", glyph: "😔", category: "smileys", keywords: "sad しょんぼり" },
  { shortcode: "sleeping", glyph: "😴", category: "smileys", keywords: "zzz 睡眠 眠い" },
  { shortcode: "mask", glyph: "😷", category: "smileys", keywords: "sick マスク 風邪" },
  { shortcode: "face_with_thermometer", glyph: "🤒", category: "smileys", keywords: "sick fever 熱 体調不良" },
  { shortcode: "dizzy_face", glyph: "😵", category: "smileys", keywords: "dizzy 目が回る" },
  { shortcode: "exploding_head", glyph: "🤯", category: "smileys", keywords: "mind blown 衝撃" },
  { shortcode: "sunglasses", glyph: "😎", category: "smileys", keywords: "cool かっこいい" },
  { shortcode: "nerd_face", glyph: "🤓", category: "smileys", keywords: "nerd めがね" },
  { shortcode: "confused", glyph: "😕", category: "smileys", keywords: "困惑 うーん" },
  { shortcode: "worried", glyph: "😟", category: "smileys", keywords: "worry 心配" },
  { shortcode: "slightly_frowning_face", glyph: "🙁", category: "smileys", keywords: "sad 残念" },
  { shortcode: "open_mouth", glyph: "😮", category: "smileys", keywords: "wow surprised びっくり" },
  { shortcode: "astonished", glyph: "😲", category: "smileys", keywords: "shocked 驚き" },
  { shortcode: "flushed", glyph: "😳", category: "smileys", keywords: "embarrassed 照れる" },
  { shortcode: "pleading_face", glyph: "🥺", category: "smileys", keywords: "please お願い うるうる" },
  { shortcode: "cry", glyph: "😢", category: "smileys", keywords: "sad tear 泣く" },
  { shortcode: "sob", glyph: "😭", category: "smileys", keywords: "cry 号泣" },
  { shortcode: "scream", glyph: "😱", category: "smileys", keywords: "fear 悲鳴" },
  { shortcode: "angry", glyph: "😠", category: "smileys", keywords: "mad 怒り" },
  { shortcode: "rage", glyph: "😡", category: "smileys", keywords: "furious 激怒" },
  { shortcode: "skull", glyph: "💀", category: "smileys", keywords: "dead 死 ヤバい" },
  { shortcode: "ghost", glyph: "👻", category: "smileys", keywords: "boo おばけ" },
  { shortcode: "robot", glyph: "🤖", category: "smileys", keywords: "bot ロボット" },
  { shortcode: "saluting_face", glyph: "🫡", category: "smileys", keywords: "salute 了解 敬礼" },
  { shortcode: "smiling_face_with_tear", glyph: "🥲", category: "smileys", keywords: "bittersweet 嬉し泣き" },
  { shortcode: "partying_face", glyph: "🥳", category: "smileys", keywords: "party celebrate お祝い" },
  { shortcode: "star_struck", glyph: "🤩", category: "smileys", keywords: "wow excited キラキラ" },
  { shortcode: "hugs", glyph: "🤗", category: "smileys", keywords: "hug ハグ" },
  { shortcode: "shushing_face", glyph: "🤫", category: "smileys", keywords: "quiet 静かに" },
  { shortcode: "zipper_mouth_face", glyph: "🤐", category: "smileys", keywords: "secret 内緒" },
  { shortcode: "melting_face", glyph: "🫠", category: "smileys", keywords: "melt とろける 暑い" },
  { shortcode: "+1", glyph: "👍", category: "gestures", keywords: "thumbsup like ok いいね 了解" },
  { shortcode: "-1", glyph: "👎", category: "gestures", keywords: "thumbsdown dislike よくない" },
  { shortcode: "ok_hand", glyph: "👌", category: "gestures", keywords: "ok perfect オッケー" },
  { shortcode: "clap", glyph: "👏", category: "gestures", keywords: "applause 拍手" },
  { shortcode: "raised_hands", glyph: "🙌", category: "gestures", keywords: "hooray やった 万歳" },
  { shortcode: "pray", glyph: "🙏", category: "gestures", keywords: "please thanks お願い ありがとう" },
  { shortcode: "wave", glyph: "👋", category: "gestures", keywords: "hello bye 手を振る" },
  { shortcode: "muscle", glyph: "💪", category: "gestures", keywords: "strong 筋肉 頑張る" },
  { shortcode: "point_up", glyph: "☝️", category: "gestures", keywords: "up 指" },
  { shortcode: "point_right", glyph: "👉", category: "gestures", keywords: "right 右" },
  { shortcode: "point_left", glyph: "👈", category: "gestures", keywords: "left 左" },
  { shortcode: "point_down", glyph: "👇", category: "gestures", keywords: "down 下" },
  { shortcode: "v", glyph: "✌️", category: "gestures", keywords: "peace ピース" },
  { shortcode: "crossed_fingers", glyph: "🤞", category: "gestures", keywords: "luck 願う" },
  { shortcode: "handshake", glyph: "🤝", category: "gestures", keywords: "deal agree 握手" },
  { shortcode: "writing_hand", glyph: "✍️", category: "gestures", keywords: "write 書く" },
  { shortcode: "eyes", glyph: "👀", category: "gestures", keywords: "look watching 見てる" },
  { shortcode: "brain", glyph: "🧠", category: "gestures", keywords: "think 脳" },
  { shortcode: "bow", glyph: "🙇", category: "gestures", keywords: "sorry thanks おじぎ すみません" },
  { shortcode: "raising_hand", glyph: "🙋", category: "gestures", keywords: "question me はい" },
  { shortcode: "shrug", glyph: "🤷", category: "gestures", keywords: "dunno さあ" },
  { shortcode: "facepalm", glyph: "🤦", category: "gestures", keywords: "oops やれやれ" },
  { shortcode: "man_technologist", glyph: "👨‍💻", category: "gestures", keywords: "coding developer エンジニア" },
  { shortcode: "woman_technologist", glyph: "👩‍💻", category: "gestures", keywords: "coding developer エンジニア" },
  { shortcode: "heart", glyph: "❤️", category: "hearts", keywords: "love ハート 好き" },
  { shortcode: "orange_heart", glyph: "🧡", category: "hearts", keywords: "love" },
  { shortcode: "yellow_heart", glyph: "💛", category: "hearts", keywords: "love" },
  { shortcode: "green_heart", glyph: "💚", category: "hearts", keywords: "love" },
  { shortcode: "blue_heart", glyph: "💙", category: "hearts", keywords: "love" },
  { shortcode: "purple_heart", glyph: "💜", category: "hearts", keywords: "love" },
  { shortcode: "black_heart", glyph: "🖤", category: "hearts", keywords: "love" },
  { shortcode: "white_heart", glyph: "🤍", category: "hearts", keywords: "love" },
  { shortcode: "broken_heart", glyph: "💔", category: "hearts", keywords: "sad 失恋" },
  { shortcode: "sparkling_heart", glyph: "💖", category: "hearts", keywords: "love キラキラ" },
  { shortcode: "heartpulse", glyph: "💗", category: "hearts", keywords: "love" },
  { shortcode: "two_hearts", glyph: "💕", category: "hearts", keywords: "love" },
  { shortcode: "fire", glyph: "🔥", category: "hearts", keywords: "lit hot 熱い 最高" },
  { shortcode: "sparkles", glyph: "✨", category: "hearts", keywords: "shiny new キラキラ" },
  { shortcode: "star", glyph: "⭐", category: "hearts", keywords: "favorite 星" },
  { shortcode: "star2", glyph: "🌟", category: "hearts", keywords: "glowing 星" },
  { shortcode: "100", glyph: "💯", category: "hearts", keywords: "perfect 百点" },
  { shortcode: "boom", glyph: "💥", category: "hearts", keywords: "explosion 爆発" },
  { shortcode: "zap", glyph: "⚡", category: "hearts", keywords: "lightning fast 稲妻" },
  { shortcode: "tada", glyph: "🎉", category: "hearts", keywords: "party celebrate 祝 おめでとう" },
  { shortcode: "confetti_ball", glyph: "🎊", category: "hearts", keywords: "party 祝" },
  { shortcode: "balloon", glyph: "🎈", category: "hearts", keywords: "party 風船" },
  { shortcode: "gift", glyph: "🎁", category: "hearts", keywords: "present プレゼント" },
  { shortcode: "trophy", glyph: "🏆", category: "hearts", keywords: "win 優勝" },
  { shortcode: "medal", glyph: "🏅", category: "hearts", keywords: "award メダル" },
  { shortcode: "white_check_mark", glyph: "✅", category: "hearts", keywords: "done check yes 完了 済み" },
  { shortcode: "heavy_check_mark", glyph: "✔️", category: "hearts", keywords: "check done チェック" },
  { shortcode: "x", glyph: "❌", category: "hearts", keywords: "no wrong バツ" },
  { shortcode: "heavy_plus_sign", glyph: "➕", category: "hearts", keywords: "plus add 追加" },
  { shortcode: "question", glyph: "❓", category: "hearts", keywords: "help 質問" },
  { shortcode: "exclamation", glyph: "❗", category: "hearts", keywords: "alert 注意" },
  { shortcode: "warning", glyph: "⚠️", category: "hearts", keywords: "caution 警告 注意" },
  { shortcode: "no_entry", glyph: "⛔", category: "hearts", keywords: "stop 禁止" },
  { shortcode: "arrow_right", glyph: "➡️", category: "hearts", keywords: "next 右" },
  { shortcode: "arrow_left", glyph: "⬅️", category: "hearts", keywords: "back 左" },
  { shortcode: "arrows_counterclockwise", glyph: "🔄", category: "hearts", keywords: "refresh retry 更新" },
  { shortcode: "recycle", glyph: "♻️", category: "hearts", keywords: "recycle リサイクル" },
  { shortcode: "bulb", glyph: "💡", category: "objects", keywords: "idea ひらめき アイデア" },
  { shortcode: "memo", glyph: "📝", category: "objects", keywords: "note メモ 書く" },
  { shortcode: "pushpin", glyph: "📌", category: "objects", keywords: "pin ピン" },
  { shortcode: "bookmark", glyph: "🔖", category: "objects", keywords: "save しおり" },
  { shortcode: "calendar", glyph: "📅", category: "objects", keywords: "date schedule 予定 カレンダー" },
  { shortcode: "clock", glyph: "🕐", category: "objects", keywords: "time 時間" },
  { shortcode: "alarm_clock", glyph: "⏰", category: "objects", keywords: "wake 目覚まし" },
  { shortcode: "hourglass", glyph: "⏳", category: "objects", keywords: "wait waiting 待ち" },
  { shortcode: "mag", glyph: "🔍", category: "objects", keywords: "search 検索" },
  { shortcode: "lock", glyph: "🔒", category: "objects", keywords: "private 鍵" },
  { shortcode: "unlock", glyph: "🔓", category: "objects", keywords: "open 解錠" },
  { shortcode: "key", glyph: "🔑", category: "objects", keywords: "password 鍵" },
  { shortcode: "bell", glyph: "🔔", category: "objects", keywords: "notification 通知" },
  { shortcode: "no_bell", glyph: "🔕", category: "objects", keywords: "mute ミュート" },
  { shortcode: "mega", glyph: "📣", category: "objects", keywords: "announce お知らせ" },
  { shortcode: "loudspeaker", glyph: "📢", category: "objects", keywords: "announce 告知" },
  { shortcode: "email", glyph: "📧", category: "objects", keywords: "mail メール" },
  { shortcode: "inbox_tray", glyph: "📥", category: "objects", keywords: "inbox 受信" },
  { shortcode: "outbox_tray", glyph: "📤", category: "objects", keywords: "outbox 送信" },
  { shortcode: "package", glyph: "📦", category: "objects", keywords: "box release リリース 荷物" },
  { shortcode: "file_folder", glyph: "📁", category: "objects", keywords: "folder フォルダ" },
  { shortcode: "page_facing_up", glyph: "📄", category: "objects", keywords: "document 書類" },
  { shortcode: "chart_with_upwards_trend", glyph: "📈", category: "objects", keywords: "growth 上昇 グラフ" },
  { shortcode: "chart_with_downwards_trend", glyph: "📉", category: "objects", keywords: "decline 下降" },
  { shortcode: "bar_chart", glyph: "📊", category: "objects", keywords: "stats グラフ" },
  { shortcode: "clipboard", glyph: "📋", category: "objects", keywords: "list クリップボード" },
  { shortcode: "computer", glyph: "💻", category: "objects", keywords: "laptop パソコン" },
  { shortcode: "desktop_computer", glyph: "🖥️", category: "objects", keywords: "pc デスクトップ" },
  { shortcode: "iphone", glyph: "📱", category: "objects", keywords: "phone スマホ" },
  { shortcode: "keyboard", glyph: "⌨️", category: "objects", keywords: "type キーボード" },
  { shortcode: "wrench", glyph: "🔧", category: "objects", keywords: "fix tool 修理 設定" },
  { shortcode: "hammer", glyph: "🔨", category: "objects", keywords: "build 工具" },
  { shortcode: "gear", glyph: "⚙️", category: "objects", keywords: "settings 設定" },
  { shortcode: "bug", glyph: "🐛", category: "objects", keywords: "bug 虫 不具合" },
  { shortcode: "rocket", glyph: "🚀", category: "objects", keywords: "launch ship deploy リリース 打ち上げ" },
  { shortcode: "construction", glyph: "🚧", category: "objects", keywords: "wip 工事中" },
  { shortcode: "books", glyph: "📚", category: "objects", keywords: "read study 本 勉強" },
  { shortcode: "moneybag", glyph: "💰", category: "objects", keywords: "money お金" },
  { shortcode: "dollar", glyph: "💵", category: "objects", keywords: "money ドル" },
  { shortcode: "yen", glyph: "💴", category: "objects", keywords: "money 円" },
  { shortcode: "shopping_cart", glyph: "🛒", category: "objects", keywords: "buy 買い物" },
  { shortcode: "battery", glyph: "🔋", category: "objects", keywords: "power 電池" },
  { shortcode: "link", glyph: "🔗", category: "objects", keywords: "url リンク" },
  { shortcode: "paperclip", glyph: "📎", category: "objects", keywords: "attach 添付" },
  { shortcode: "camera", glyph: "📷", category: "objects", keywords: "photo 写真" },
  { shortcode: "movie_camera", glyph: "🎥", category: "objects", keywords: "video 動画" },
  { shortcode: "microphone", glyph: "🎤", category: "objects", keywords: "sing mic マイク" },
  { shortcode: "headphones", glyph: "🎧", category: "objects", keywords: "music 音楽" },
  { shortcode: "musical_note", glyph: "🎵", category: "objects", keywords: "music 音楽" },
  { shortcode: "art", glyph: "🎨", category: "objects", keywords: "design 絵" },
  { shortcode: "game_die", glyph: "🎲", category: "objects", keywords: "random サイコロ" },
  { shortcode: "soccer", glyph: "⚽", category: "objects", keywords: "football サッカー" },
  { shortcode: "baseball", glyph: "⚾", category: "objects", keywords: "野球" },
  { shortcode: "basketball", glyph: "🏀", category: "objects", keywords: "バスケ" },
  { shortcode: "sunny", glyph: "☀️", category: "nature", keywords: "sun 晴れ" },
  { shortcode: "cloud", glyph: "☁️", category: "nature", keywords: "cloudy 曇り" },
  { shortcode: "umbrella", glyph: "☔", category: "nature", keywords: "rain 雨 傘" },
  { shortcode: "snowflake", glyph: "❄️", category: "nature", keywords: "cold snow 雪" },
  { shortcode: "rainbow", glyph: "🌈", category: "nature", keywords: "虹" },
  { shortcode: "seedling", glyph: "🌱", category: "nature", keywords: "plant new 芽" },
  { shortcode: "four_leaf_clover", glyph: "🍀", category: "nature", keywords: "luck クローバー" },
  { shortcode: "cherry_blossom", glyph: "🌸", category: "nature", keywords: "sakura 桜 春" },
  { shortcode: "maple_leaf", glyph: "🍁", category: "nature", keywords: "autumn 紅葉" },
  { shortcode: "palm_tree", glyph: "🌴", category: "nature", keywords: "vacation 休暇 ヤシ" },
  { shortcode: "dog", glyph: "🐶", category: "nature", keywords: "puppy 犬" },
  { shortcode: "cat", glyph: "🐱", category: "nature", keywords: "kitty 猫" },
  { shortcode: "mouse", glyph: "🐭", category: "nature", keywords: "ねずみ" },
  { shortcode: "rabbit", glyph: "🐰", category: "nature", keywords: "bunny うさぎ" },
  { shortcode: "bear", glyph: "🐻", category: "nature", keywords: "くま" },
  { shortcode: "panda_face", glyph: "🐼", category: "nature", keywords: "パンダ" },
  { shortcode: "fox_face", glyph: "🦊", category: "nature", keywords: "きつね" },
  { shortcode: "pig", glyph: "🐷", category: "nature", keywords: "ぶた" },
  { shortcode: "cow", glyph: "🐮", category: "nature", keywords: "うし" },
  { shortcode: "monkey_face", glyph: "🐵", category: "nature", keywords: "さる" },
  { shortcode: "chicken", glyph: "🐔", category: "nature", keywords: "にわとり" },
  { shortcode: "penguin", glyph: "🐧", category: "nature", keywords: "ペンギン" },
  { shortcode: "bird", glyph: "🐦", category: "nature", keywords: "鳥" },
  { shortcode: "fish", glyph: "🐟", category: "nature", keywords: "魚" },
  { shortcode: "whale", glyph: "🐳", category: "nature", keywords: "くじら" },
  { shortcode: "dolphin", glyph: "🐬", category: "nature", keywords: "イルカ" },
  { shortcode: "turtle", glyph: "🐢", category: "nature", keywords: "かめ" },
  { shortcode: "snake", glyph: "🐍", category: "nature", keywords: "へび python" },
  { shortcode: "bee", glyph: "🐝", category: "nature", keywords: "はち" },
  { shortcode: "butterfly", glyph: "🦋", category: "nature", keywords: "ちょう" },
  { shortcode: "dragon", glyph: "🐉", category: "nature", keywords: "龍" },
  { shortcode: "unicorn", glyph: "🦄", category: "nature", keywords: "ユニコーン" },
  { shortcode: "apple", glyph: "🍎", category: "food", keywords: "りんご" },
  { shortcode: "banana", glyph: "🍌", category: "food", keywords: "バナナ" },
  { shortcode: "strawberry", glyph: "🍓", category: "food", keywords: "いちご" },
  { shortcode: "watermelon", glyph: "🍉", category: "food", keywords: "すいか" },
  { shortcode: "rice_ball", glyph: "🍙", category: "food", keywords: "onigiri おにぎり" },
  { shortcode: "bento", glyph: "🍱", category: "food", keywords: "lunch 弁当 昼休み" },
  { shortcode: "ramen", glyph: "🍜", category: "food", keywords: "noodle ラーメン" },
  { shortcode: "sushi", glyph: "🍣", category: "food", keywords: "寿司" },
  { shortcode: "curry", glyph: "🍛", category: "food", keywords: "カレー" },
  { shortcode: "rice", glyph: "🍚", category: "food", keywords: "ごはん" },
  { shortcode: "dango", glyph: "🍡", category: "food", keywords: "だんご" },
  { shortcode: "oden", glyph: "🍢", category: "food", keywords: "おでん" },
  { shortcode: "pizza", glyph: "🍕", category: "food", keywords: "ピザ" },
  { shortcode: "hamburger", glyph: "🍔", category: "food", keywords: "burger ハンバーガー" },
  { shortcode: "fries", glyph: "🍟", category: "food", keywords: "ポテト" },
  { shortcode: "bread", glyph: "🍞", category: "food", keywords: "パン" },
  { shortcode: "egg", glyph: "🥚", category: "food", keywords: "たまご" },
  { shortcode: "cake", glyph: "🍰", category: "food", keywords: "ケーキ" },
  { shortcode: "birthday", glyph: "🎂", category: "food", keywords: "birthday 誕生日" },
  { shortcode: "cookie", glyph: "🍪", category: "food", keywords: "クッキー" },
  { shortcode: "doughnut", glyph: "🍩", category: "food", keywords: "ドーナツ" },
  { shortcode: "chocolate_bar", glyph: "🍫", category: "food", keywords: "チョコ" },
  { shortcode: "icecream", glyph: "🍦", category: "food", keywords: "アイス" },
  { shortcode: "coffee", glyph: "☕", category: "food", keywords: "break コーヒー 休憩" },
  { shortcode: "tea", glyph: "🍵", category: "food", keywords: "green tea お茶" },
  { shortcode: "beer", glyph: "🍺", category: "food", keywords: "drink ビール 乾杯" },
  { shortcode: "beers", glyph: "🍻", category: "food", keywords: "cheers 乾杯" },
  { shortcode: "wine_glass", glyph: "🍷", category: "food", keywords: "ワイン" },
  { shortcode: "sake", glyph: "🍶", category: "food", keywords: "日本酒" },
  { shortcode: "cup_with_straw", glyph: "🥤", category: "food", keywords: "drink ジュース" },
  { shortcode: "house", glyph: "🏠", category: "travel", keywords: "home 家 在宅" },
  { shortcode: "office", glyph: "🏢", category: "travel", keywords: "work 会社 オフィス" },
  { shortcode: "hospital", glyph: "🏥", category: "travel", keywords: "病院" },
  { shortcode: "school", glyph: "🏫", category: "travel", keywords: "学校" },
  { shortcode: "convenience_store", glyph: "🏪", category: "travel", keywords: "コンビニ" },
  { shortcode: "mount_fuji", glyph: "🗻", category: "travel", keywords: "富士山" },
  { shortcode: "tokyo_tower", glyph: "🗼", category: "travel", keywords: "東京タワー" },
  { shortcode: "shinto_shrine", glyph: "⛩️", category: "travel", keywords: "神社" },
  { shortcode: "car", glyph: "🚗", category: "travel", keywords: "drive 車" },
  { shortcode: "bus", glyph: "🚌", category: "travel", keywords: "commute 移動 バス" },
  { shortcode: "train", glyph: "🚃", category: "travel", keywords: "電車 通勤" },
  { shortcode: "bullettrain_front", glyph: "🚅", category: "travel", keywords: "新幹線" },
  { shortcode: "bike", glyph: "🚲", category: "travel", keywords: "自転車" },
  { shortcode: "airplane", glyph: "✈️", category: "travel", keywords: "flight trip 飛行機 出張" },
  { shortcode: "ship", glyph: "🚢", category: "travel", keywords: "船" },
  { shortcode: "taxi", glyph: "🚕", category: "travel", keywords: "タクシー" },
  { shortcode: "earth_asia", glyph: "🌏", category: "travel", keywords: "world 地球" },
  { shortcode: "world_map", glyph: "🗺️", category: "travel", keywords: "map 地図" },
  { shortcode: "jp", glyph: "🇯🇵", category: "flags", keywords: "japan 日本" },
  { shortcode: "us", glyph: "🇺🇸", category: "flags", keywords: "usa アメリカ" },
  { shortcode: "gb", glyph: "🇬🇧", category: "flags", keywords: "uk イギリス" },
  { shortcode: "kr", glyph: "🇰🇷", category: "flags", keywords: "korea 韓国" },
  { shortcode: "cn", glyph: "🇨🇳", category: "flags", keywords: "china 中国" },
  { shortcode: "checkered_flag", glyph: "🏁", category: "flags", keywords: "finish ゴール" },
  { shortcode: "triangular_flag_on_post", glyph: "🚩", category: "flags", keywords: "flag red 旗" },
];
